services:
  mysql:
    image: mysql:8.0
    container_name: shophouse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shophouse
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shophouse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    image: kareemzaher/shophouse-app:latest
    container_name: shophouse-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - shophouse-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  shophouse-network:
    driver: bridge